#!/bin/bash

set -e

# Get rid of old install maybe
if [ -d venv ]; then
    rm -rf venv
fi

# Reset / grab a new one
virtualenv venv
source venv/bin/activate
pip install jupyter notebook
jupyter nbextension enable --py --sys-prefix widgetsnbextension
pip install -e git+https://github.com/azavea/ipyleaflet#egg=9cfd238

# MacOS has some sort of messy openSSL incompatibility
# See https://github.com/pyca/cryptography/issues/3489
if [ "$(uname -s)" == "Darwin" ]; then
    pip install cryptography \
        --global-option=build_ext \
        --global-option="-L/usr/local/opt/openssl/lib" \
        --global-option="-I/usr/local/opt/openssl/include"
fi

jupyter nbextension install --py --symlink --sys-prefix ipyleaflet
jupyter nbextension enable --py --sys-prefix ipyleaflet

python setup.py develop
